x-loki-options: &default-options
  loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
  loki-batch-size: "100"
  loki-retries: "2"
  loki-max-backoff: "1000ms"
  loki-timeout: "1s"

x-loki-logging: &default-logging
  driver: "loki"
  options:
    <<: *default-options

services:
    laravel:
        build:
            context: './backend/vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        container_name: tunehub-laravel
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8080:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        logging:
          <<: *default-logging
          options:
            <<: *default-options
            loki-external-labels: "service=laravel,project=tunehub,env=local"
        volumes:
            - './backend:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - minio
    nginx:
        image: nginx:latest
        container_name: tunehub-nginx
        ports:
            - "80:80"
        logging:
          <<: *default-logging
          options:
            <<: *default-options
            loki-external-labels: "service=nginx,project=tunehub,env=local"
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel
        networks:
            - sail
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: tunehub-frontend-1
        ports:
            - '5175:5175'
        logging:
          <<: *default-logging
          options:
            <<: *default-options
            loki-external-labels: "service=frontend,project=tunehub,env=local"
        volumes:
            - ./frontend:/app
            - frontend-node-modules:/app/node_modules
        networks:
            - sail
        depends_on:
            - laravel
    mysql:
        image: 'mysql:8.4'
        container_name: tunehub-mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        logging:
          <<: *default-logging
          options:
            <<: *default-options
            loki-external-labels: "service=mysql,project=tunehub,env=local"
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    clickhouse:
        image: clickhouse/clickhouse-server:24
        container_name: tunehub-clickhouse-1
        cap_add:
          - SYS_NICE
        environment:
            CLICKHOUSE_PASSWORD: '${CLICKHOUSE_PASSWORD}'
            CLICKHOUSE_USER: '${CLICKHOUSE_USER}'
            CLICKHOUSE_DB: '${CLICKHOUSE_DB}'
        logging:
          <<: *default-logging
          options:
            <<: *default-options
            loki-external-labels: "service=clickhouse,project=tunehub,env=local"
        ports:
            - "8123:8123"
            - "9009:9009"
        volumes:
            - clickhouse-data:/var/lib/clickhouse
        networks:
            - sail
    redis:
        image: 'redis:7-alpine'
        container_name: tunehub-redis-1
        ports:
          - '6379:6379'
        logging:
          <<: *default-logging
          options:
            <<: *default-options
            loki-external-labels: "service=redis,project=tunehub,env=local"
        volumes:
          - 'redis-data:/data'
        networks:
          - sail
        healthcheck:
          test: ['CMD', 'redis-cli', 'ping']
          retries: 3
          timeout: 5s
    minio:
        image: 'minio/minio:RELEASE.2025-04-22T22-12-26Z'
        container_name: tunehub-minio
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-9001}:9001'
        environment:
            MINIO_ROOT_USER: '${AWS_ACCESS_KEY_ID}'
            MINIO_ROOT_PASSWORD: '${AWS_SECRET_ACCESS_KEY}'
        logging:
          <<: *default-logging
          options:
            <<: *default-options
            loki-external-labels: "service=minio,project=tunehub,env=local"
        volumes:
            - 'sail-minio:/data'
        networks:
            - sail
        command: 'minio server /data --console-address ":9001"'
        healthcheck:
            test:
                - CMD
                - mc
                - ready
                - local
            retries: 3
            timeout: 5s
    loki:
        image: grafana/loki:3.5.5
        container_name: tunehub-loki
        ports:
          - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
    grafana:
        image: grafana/grafana:12.2.0
        container_name: tunehub-grafana
        ports:
          - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
        volumes:
          - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        depends_on:
        - loki
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-minio:
        driver: local
    frontend-node-modules:
        driver: local
    redis-data:
        driver: local
    clickhouse-data:
        driver: local